import {
  contentBounds,
  defineProgram,
  generateDragonCurve,
  intParam,
  plotPalette,
} from "@ligneclaire/sdk";

const canvas = {
  widthMm: 297,
  heightMm: 210,
  marginMm: 10,
} as const;

export const dragonCurveParamSchema = {
  iterations: intParam({
    min: 1,
    max: 16,
    default: 12,
    label: "Iterations",
    group: "Curve",
  }),
} as const;

export const program = defineProgram({
  id: "dragon-curve",
  title: "Dragon Curve",
  description: "A Heighway dragon generated by an L-system and fitted to the printable sheet.",
  version: "1.0.0",
  canvas,
  params: dragonCurveParamSchema,
  validation: {
    cases: ["default"],
  },
  render(ctx) {
    const curve = generateDragonCurve(ctx.params.iterations, contentBounds(canvas));

    return {
      canvas,
      layers: [
        {
          id: "dragon-curve",
          label: "Dragon Curve",
          stroke: plotPalette.primary,
          paths: [curve],
        },
      ],
      metadata: {
        programId: "dragon-curve",
        version: "1.0.0",
        mode: ctx.mode,
      },
    };
  },
});
