import { mkdir, readdir, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const programsDir = path.join(rootDir, "programs");
const outputPath = path.join(
  rootDir,
  "programs/generated/program-registry.ts"
);

type ProgramEntry = {
  importName: string;
  importPath: string;
  folderName: string;
  programId: string;
};

const requiredFiles = ["index.ts", "README.md", path.join("params", "default.json")];

function isProgramFolder(name: string): boolean {
  return !name.startsWith(".") && name !== "generated";
}

function toImportName(folderName: string): string {
  return folderName
    .replace(/[^A-Za-z0-9]/g, " ")
    .trim()
    .split(/\s+/)
    .map((segment, index) =>
      index === 0
        ? segment.toLowerCase()
        : `${segment.slice(0, 1).toUpperCase()}${segment.slice(1).toLowerCase()}`
    )
    .join("");
}

async function assertRequiredFiles(folderPath: string): Promise<void> {
  for (const fileName of requiredFiles) {
    const target = path.join(folderPath, fileName);
    try {
      const targetStat = await stat(target);
      if (!targetStat.isFile()) {
        throw new Error(`${target} exists but is not a file`);
      }
    } catch (error) {
      throw new Error(`Missing required program file: ${path.relative(rootDir, target)}`, {
        cause: error,
      });
    }
  }
}

async function collectPrograms(): Promise<ProgramEntry[]> {
  const dirents = await readdir(programsDir, { withFileTypes: true });
  const folders = dirents.filter((entry) => entry.isDirectory() && isProgramFolder(entry.name));

  const programs: ProgramEntry[] = [];
  const ids = new Set<string>();

  for (const folder of folders) {
    const folderPath = path.join(programsDir, folder.name);
    await assertRequiredFiles(folderPath);
    const moduleUrl = pathToFileURL(path.join(folderPath, "index.ts")).href;
    const module = (await import(moduleUrl)) as { program?: { id?: string } };
    const programId = module.program?.id;

    if (!programId) {
      throw new Error(`Program module ${path.relative(rootDir, folderPath)} does not export program.id`);
    }

    if (programId !== folder.name) {
      throw new Error(
        `Program folder "${folder.name}" must match program id "${programId}".`
      );
    }

    if (ids.has(programId)) {
      throw new Error(`Duplicate program id "${programId}" detected while generating the registry.`);
    }

    ids.add(programId);
    programs.push({
      folderName: folder.name,
      programId,
      importName: `${toImportName(folder.name)}Program`,
      importPath: `../${folder.name}/index`,
    });
  }

  return programs.sort((left, right) => left.folderName.localeCompare(right.folderName));
}

function renderRegistry(entries: ProgramEntry[]): string {
  const imports = entries
    .map((entry) => `import { program as ${entry.importName} } from "${entry.importPath}";`)
    .join("\n");

  const registry = entries.map((entry) => entry.importName).join(", ");

  return `/* eslint-disable */
// This file is generated by scripts/generate-program-registry.ts.
// Do not edit it manually.

import type { ProgramDefinition } from "@ligneclaire/sdk";
${imports ? `\n${imports}\n` : ""}
export const programRegistry = [${registry}] as const satisfies readonly ProgramDefinition<any, any>[];
`;
}

async function main(): Promise<void> {
  const entries = await collectPrograms();
  await mkdir(path.dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderRegistry(entries), "utf8");
  process.stdout.write(`Generated registry with ${entries.length} program(s) at ${path.relative(rootDir, outputPath)}\n`);
}

await main();
